Repository HanaPiece/hana-piece-server, pull requests merged in 2024-06, with the labels that each got.

#33 feat/유저 정보 조회 및 월급 수정
  src/main/java/com/project/hana_piece/goal/controller/UserGoalController.java
  src/main/java/com/project/hana_piece/goal/dto/ApartmentPricePredictRequest.java
  src/main/java/com/project/hana_piece/goal/dto/UserGoalDetailGetResponse.java
  src/main/java/com/project/hana_piece/goal/service/ApartmentService.java
  src/main/java/com/project/hana_piece/user/controller/UserController.java
  src/main/java/com/project/hana_piece/user/domain/User.java
  src/main/java/com/project/hana_piece/user/dto/UserGetResponse.java
  src/main/java/com/project/hana_piece/user/dto/UserLoginResponse.java
  src/main/java/com/project/hana_piece/user/dto/UserSalaryGetResponse.java
  src/main/java/com/project/hana_piece/user/dto/UserSalaryUpsertRequest.java
  src/main/java/com/project/hana_piece/user/dto/UserSalaryUpsertResponse.java
  src/main/java/com/project/hana_piece/user/repository/UserRepository.java
  src/main/java/com/project/hana_piece/user/service/UserService.java
Labels: enhancement

#34 feat: 상품 가입 구현
  src/main/java/com/project/hana_piece/account/domain/Account.java
  src/main/java/com/project/hana_piece/product/domain/EnrolledProduct.java
  src/main/java/com/project/hana_piece/product/dto/EnrollProductRequest.java
  src/main/java/com/project/hana_piece/product/exception/InstallmentSavingNotFoundException.java
  src/main/java/com/project/hana_piece/product/exception/SavingNotFoundException.java
  src/main/java/com/project/hana_piece/product/service/ProductService.java
Labels: enhancement

#37 feat: 가입한 적금 처리
  src/main/java/com/project/hana_piece/product/exception/AlreadyEnrolledProductException.java
  src/main/java/com/project/hana_piece/product/repository/EnrolledProductRepository.java
  src/main/java/com/project/hana_piece/product/service/ProductService.java
Labels: enhancement

#39 refactor: stream을 사용하여 코드 변경
  src/main/java/com/project/hana_piece/product/service/ProductService.java
Labels: refactor

#41 feat/유저 목표 - 유저 목표 별칭 컬럼 추가 관련 코드 수정
  src/main/java/com/project/hana_piece/goal/domain/UserGoal.java
  src/main/java/com/project/hana_piece/goal/dto/UserGoalDetailGetResponse.java
  src/main/java/com/project/hana_piece/goal/dto/UserGoalGetResponse.java
  src/main/java/com/project/hana_piece/goal/dto/UserGoalUpsertRequest.java
  src/main/java/com/project/hana_piece/goal/service/UserGoalService.java
  src/main/resources/ddl.sql
  src/main/resources/insert-domain-data.sql
Labels: enhancement

#43 feat/유저 목표 - 유저 목표 리스트 상세 정보 조회
  src/main/java/com/project/hana_piece/goal/controller/UserGoalController.java
  src/main/java/com/project/hana_piece/goal/dto/UserGoalListGetResponse.java
  src/main/java/com/project/hana_piece/goal/projection/UserGoalSummary.java
  src/main/java/com/project/hana_piece/goal/repository/UserGoalRepository.java
  src/main/java/com/project/hana_piece/goal/service/UserGoalService.java
Labels: enhancement

#46 feat/#15 구조화 된 응답을 위한 프롬프트 관리 클래스 생성 & AI API 온도 매개변수 값 조정
  src/main/java/com/project/hana_piece/ai/dto/GeminiCallRequest.java
  src/main/java/com/project/hana_piece/ai/service/AiServiceImpl.java
  src/main/java/com/project/hana_piece/ai/vo/GeminiPrompt.java
  src/main/java/com/project/hana_piece/common/util/JsonUtil.java
  src/main/java/com/project/hana_piece/goal/service/ApartmentService.java
  src/main/java/com/project/hana_piece/product/domain/EnrolledProduct.java
  src/main/java/com/project/hana_piece/product/service/ProductService.java
Labels: enhancement

#51 feat/유저 목표 수정 - 아파트, 차 ID 추가 및 목표 리스트 상세 조회 타입코드, SpecificId 추가
  src/main/java/com/project/hana_piece/goal/dto/ApartmentGetResponse.java
  src/main/java/com/project/hana_piece/goal/dto/CarGetResponse.java
  src/main/java/com/project/hana_piece/goal/dto/UserGoalListGetResponse.java
  src/main/java/com/project/hana_piece/goal/projection/UserGoalSummary.java
  src/main/java/com/project/hana_piece/goal/repository/UserGoalRepository.java
Labels: enhancement

#53 feat/#16 QueryDSL 설정
  build.gradle
  src/main/java/com/project/hana_piece/account/repository/AccountTransactionRepositoryCustom.java
  src/main/java/com/project/hana_piece/account/service/AccountService.java
  src/main/java/com/project/hana_piece/common/config/QueryDSLConfig.java
Labels: enhancement

#55 feat/쿼리 DDL 수정
  src/main/resources/apartments.csv
  src/main/resources/insert-car-data.sql
  src/main/resources/insert-domain-data.sql
  src/main/resources/insert-type-data.sql
Labels: enhancement

#56 feat/#54 응답 DTO에 해당 월 자동 이체 금액 추가 & 년 + 월 데이터를 입력 받아 처리
  src/main/java/com/project/hana_piece/account/controller/AccountController.java
  src/main/java/com/project/hana_piece/account/dto/AccountMonthTransactionGetResponse.java
  src/main/java/com/project/hana_piece/account/repository/AccountTransactionRepository.java
  src/main/java/com/project/hana_piece/account/repository/AccountTransactionRepositoryCustom.java
  src/main/java/com/project/hana_piece/account/service/AccountService.java
Labels: enhancement

#58 feat/#57 logging
  .gitignore
  src/main/resources/logback-spring.xml
Labels: enhancement

#62 feat/#60 스케쥴링을 통한 자동이체 시스템 구현
  src/main/java/com/project/hana_piece/HanaPieceApplication.java
  src/main/java/com/project/hana_piece/account/controller/AccountController.java
  src/main/java/com/project/hana_piece/account/domain/Account.java
  src/main/java/com/project/hana_piece/account/domain/AccountTransaction.java
  src/main/java/com/project/hana_piece/account/repository/AccountAutoDebitRepository.java
  src/main/java/com/project/hana_piece/account/service/AccountService.java
  src/main/java/com/project/hana_piece/common/scheduler/AutoDebitScheduler.java
Labels: enhancement

#64 Feat/promptmessage
  src/main/java/com/project/hana_piece/product/service/ProductService.java
Labels: enhancement

#65 feat/목표 리스트 상세 조회 enrolledId 추가 및 목표에 대한 계좌 정보 조회 계좌 1개 오류 해결
  src/main/java/com/project/hana_piece/account/repository/AccountRepository.java
  src/main/java/com/project/hana_piece/goal/dto/UserGoalListGetResponse.java
  src/main/java/com/project/hana_piece/goal/projection/UserGoalSummary.java
  src/main/java/com/project/hana_piece/goal/repository/UserGoalRepository.java
  src/main/java/com/project/hana_piece/goal/service/UserGoalService.java
Labels: bug, documentation
